### ISSUE TITLE
Ver.6 HP作成

### ISSUE THREAD

**Issue by rkonno** [takizawa-hackathon/takizawa-hackathon.github.io#90]
## Doneの定義
https://takizawa-hackathon.com/ （トップページ）がVer.6のイベント募集ページに変更されている

## 期日
4/3（水）

## スクリーンショット

![Image](https://github.com/takizawa-hackathon/takizawa-hackathon.github.io/assets/12765236/8f63cb0f-1e88-41ca-bf6b-509f6a87898d)

**Comment by sasakitomohiro** [comment]
こちら完了しているためcloseします！
